FROM UPSTREAM_REPO

ARG PHP_VERSION
ENV PHP_VERSION=$PHP_VERSION

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm

RUN apt-get update && apt-get --no-install-recommends --no-install-suggests -y install \
    procps \
    curl \
    ca-certificates \
    apt-transport-https \
    wget && \
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
    echo "deb https://packages.sury.org/php/ jessie main" > /etc/apt/sources.list.d/php.list
RUN bash -x -c "apt-get update && apt-get --no-install-recommends --no-install-suggests -y install \
    less \
    git \
    mysql-client \
    $PHP_VERSION-curl \
    $PHP_VERSION-cgi \
    $PHP_VERSION-cli \
    $PHP_VERSION-common \
    $PHP_VERSION-fpm \
    $PHP_VERSION-gd \
    $PHP_VERSION-json \
    $PHP_VERSION-mysql \
    $PHP_VERSION-mbstring \
    $PHP_VERSION-xml \
    $PHP_VERSION-xmlrpc \
    $PHP_VERSION-mcrypt \
    $PHP_VERSION-opcache \
    $PHP_VERSION-soap \
    $PHP_VERSION-readline && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*"
